# Generated by Django 5.1 on 2024-09-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileyoutube',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
